/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ia;

import java.awt.Color;

/**
 *
 * @author rafik
 */
public class Jogo extends javax.swing.JFrame {
    Main meuJogo = new Main();
    public String modo,nivel; 
    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();
    }
    public Jogo(String modo, String nivel){
        initComponents();
        this.modo = modo;
        this.nivel = nivel;
        meuJogo.iniciaTabuleiro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(5, 5));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton1.setText("X");
        jButton1.setEnabled(false);
        getContentPane().add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton2.setText("-");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton3.setText("X");
        jButton3.setEnabled(false);
        getContentPane().add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton5.setText("X");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        getContentPane().add(jButton7);

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton11.setText("X");
        jButton11.setEnabled(false);
        getContentPane().add(jButton11);

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);

        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton13.setText("X");
        jButton13.setEnabled(false);
        getContentPane().add(jButton13);

        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);

        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton15.setText("X");
        jButton15.setEnabled(false);
        getContentPane().add(jButton15);

        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        getContentPane().add(jButton17);

        jButton18.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);

        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        getContentPane().add(jButton19);

        jButton20.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);

        jButton21.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton21.setText("X");
        jButton21.setEnabled(false);
        getContentPane().add(jButton21);

        jButton22.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);

        jButton23.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton23.setText("X");
        jButton23.setEnabled(false);
        getContentPane().add(jButton23);

        jButton24.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);

        jButton25.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton25.setText("X");
        jButton25.setEnabled(false);
        getContentPane().add(jButton25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton4.setText("-");
        jButton4.setEnabled(false);
        
        if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
            jButton9.setBackground(Color.red);
            
        }
        int[] move = meuJogo.main(modo, nivel, 0, 3);
        
        for(int i = 0 ; i < move.length-1; i = i + 2){
            
        
        if(move[i] == 0 && move[i+1] == 3){
            jButton4.setText("-");
            jButton4.setEnabled(false);
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
            jButton9.setBackground(Color.BLUE);
            
        }
           
        }
        if(move[i] == 1 && move[i+1] == 0){
            jButton6.setText("|");
            jButton6.setEnabled(false);
            if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
            jButton7.setBackground(Color.BLUE);
        }
         
        }
        if(move[i] == 1 && move[i+1] ==2){
            jButton8.setText("|");
            jButton8.setEnabled(false);
            if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
            jButton7.setBackground(Color.BLUE);
        }
        if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
            jButton9.setBackground(Color.BLUE);
            
        }
        }
        if(move[i] == 1 && move[i+1] ==4){
            jButton10.setText("|");
            jButton10.setEnabled(false);
           if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
            jButton9.setBackground(Color.BLUE);
            
        }
        }
        if(move[i] == 2 && move[i+1] == 1 ){
            jButton12.setText("-");
            jButton12.setEnabled(false);

            if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
                
            }
           
             if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.BLUE);
        
        }

        }
        if(move[i] == 2 && move[i+1] == 3){
            jButton14.setText("-");
            jButton14.setEnabled(false);
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }

             if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.BLUE);
        }
        }
        if(move[i] == 3 && move[i+1] == 0){
            jButton16.setText("|");
            jButton16.setEnabled(false);
          if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.BLUE);
        }
        }
        if(move[i] == 3 && move[i+1] ==2){
            jButton18.setText("|");
            jButton18.setEnabled(false);
            if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
                
            }
           
             if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.BLUE);
        }
        }
        if(move[i] == 3 && move[i+1] ==4){
            jButton20.setText("|");
            jButton20.setEnabled(false);
          
         
             if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.BLUE);
        }
        }if(move[i] == 4 && move[i+1] == 1 ){
            jButton22.setText("-");
            jButton22.setEnabled(false);
         
          
             if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.BLUE);
        }
        }
        if(move[i] == 4 && move[i+1] == 3){
            jButton24.setText("-");
            jButton24.setEnabled(false);
        
             if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.BLUE);
        }
        }
        } 
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       jButton8.setText("|");
        jButton8.setEnabled(false);
        if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
            jButton7.setBackground(Color.red);
            
        }
        if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
            jButton9.setBackground(Color.red);
            
        }
        int[] move = meuJogo.main(modo, nivel, 1, 2);
        
        for(int i = 0 ; i < move.length-1; i = i + 2){
            
        
            if(move[i] == 0 && move[i+1] == 3){
                jButton4.setText("-");
                jButton4.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
        }
            if(move[i] == 1 && move[i+1] == 0){
            jButton6.setText("|");
            jButton6.setEnabled(false);
            if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
            jButton7.setBackground(Color.BLUE);
        }
         
        }
            if(move[i] == 1 && move[i+1] ==2){
                jButton8.setText("|");
                jButton8.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 1 && move[i+1] ==4){
                jButton10.setText("|");
                jButton10.setEnabled(false);
               if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 2 && move[i+1] == 1 ){
                System.out.println("Entrou");
                jButton12.setText("-");
                jButton12.setEnabled(false);
    
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                    jButton7.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            
            }
    
            }
            if(move[i] == 2 && move[i+1] == 3){
                jButton14.setText("-");
                jButton14.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                    jButton9.setBackground(Color.BLUE);
                    
                }
    
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] == 0){
                jButton16.setText("|");
                jButton16.setEnabled(false);
              if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==2){
                jButton18.setText("|");
                jButton18.setEnabled(false);
                if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                    jButton19.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==4){
                jButton20.setText("|");
                jButton20.setEnabled(false);
              
             
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
        }
            if(move[i] == 4 && move[i+1] == 3){
                jButton24.setText("-");
                jButton24.setEnabled(false);
            
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       jButton6.setText("|");
        jButton6.setEnabled(false);
        if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
            jButton7.setBackground(Color.red);
            
        }
        int[] move = meuJogo.main(modo, nivel, 1, 0);
        
         for(int i = 0 ; i < move.length-1; i = i + 2){
            
        
            if(move[i] == 0 && move[i+1] == 3){
                jButton4.setText("-");
                jButton4.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
                if(move[i] == 1 && move[i+1] == 0){
            jButton6.setText("|");
            jButton6.setEnabled(false);
            if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
            jButton7.setBackground(Color.BLUE);
        }
         
        }
            if(move[i] == 1 && move[i+1] ==2){
                jButton8.setText("|");
                jButton8.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 1 && move[i+1] ==4){
                jButton10.setText("|");
                jButton10.setEnabled(false);
               if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 2 && move[i+1] == 1 ){
                jButton12.setText("-");
                jButton12.setEnabled(false);
    
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                    jButton7.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            
            }
    
            }
            if(move[i] == 2 && move[i+1] == 3){
                jButton14.setText("-");
                jButton14.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                    jButton9.setBackground(Color.BLUE);
                    
                }
    
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] == 0){
                jButton16.setText("|");
                jButton16.setEnabled(false);
              if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
        }
        if(move[i] == 3 && move[i+1] ==2){
            jButton18.setText("|");
            jButton18.setEnabled(false);
            if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
                
            }
           
             if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.BLUE);
        }
        }
        if(move[i] == 3 && move[i+1] ==4){
            jButton20.setText("|");
            jButton20.setEnabled(false);
          
         
             if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.BLUE);
             }
        }if(move[i] == 4 && move[i+1] == 1 ){
            jButton22.setText("-");
            jButton22.setEnabled(false);
         
          
             if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.BLUE);
        }
        }
        
        if(move[i] == 4 && move[i+1] == 3){
            jButton24.setText("-");
            jButton24.setEnabled(false);
        
             if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.BLUE);
        }
        }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jButton10.setText("|");
        jButton10.setEnabled(false);
        if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
            jButton9.setBackground(Color.red);
            
        }
        int[] move = meuJogo.main(modo, nivel, 1, 4);
        
        for(int i = 0 ; i < move.length-1; i = i + 2){
            
        
            if(move[i] == 0 && move[i+1] == 3){
                jButton4.setText("-");
                jButton4.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
            }
        }
            if(move[i] == 1 && move[i+1] == 0){
            jButton6.setText("|");
            jButton6.setEnabled(false);
            if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
            jButton7.setBackground(Color.BLUE);
        }
         
        }
            if(move[i] == 1 && move[i+1] ==2){
                jButton8.setText("|");
                jButton8.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 1 && move[i+1] ==4){
                jButton10.setText("|");
                jButton10.setEnabled(false);
               if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 2 && move[i+1] == 1 ){
                jButton12.setText("-");
                jButton12.setEnabled(false);
    
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                    jButton7.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            
            }
    
            }
            if(move[i] == 2 && move[i+1] == 3){
                jButton14.setText("-");
                jButton14.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                    jButton9.setBackground(Color.BLUE);
                    
                }
    
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] == 0){
                jButton16.setText("|");
                jButton16.setEnabled(false);
              if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==2){
                jButton18.setText("|");
                jButton18.setEnabled(false);
                if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                    jButton19.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==4){
                jButton20.setText("|");
                jButton20.setEnabled(false);
              
             
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
                 }
            }if(move[i] == 4 && move[i+1] == 1 ){
                jButton22.setText("-");
                jButton22.setEnabled(false);
             
              
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 4 && move[i+1] == 3){
                jButton24.setText("-");
                jButton24.setEnabled(false);
            
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jButton12.setText("-");
        jButton12.setEnabled(false);
        if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
            jButton7.setBackground(Color.red);
            
        }
        if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.red);
            
        }
        int[] move = meuJogo.main(modo, nivel, 2, 1);
        
        for(int i = 0 ; i < move.length-1; i = i + 2){
            
        
            if(move[i] == 0 && move[i+1] == 3){
                jButton4.setText("-");
                jButton4.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
        }
            if(move[i] == 1 && move[i+1] == 0){
            jButton6.setText("|");
            jButton6.setEnabled(false);
            if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
            jButton7.setBackground(Color.BLUE);
        }
         
        }
            if(move[i] == 1 && move[i+1] ==2){
                jButton8.setText("|");
                jButton8.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
        
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
        }
            if(move[i] == 1 && move[i+1] ==4){
                jButton10.setText("|");
                jButton10.setEnabled(false);
               if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 2 && move[i+1] == 1 ){
                jButton12.setText("-");
                jButton12.setEnabled(false);
    
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                    jButton7.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            
            }
    
            }
            if(move[i] == 2 && move[i+1] == 3){
                jButton14.setText("-");
                jButton14.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                    jButton9.setBackground(Color.BLUE);
                    
                }
    
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] == 0){
                jButton16.setText("|");
                jButton16.setEnabled(false);
              if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==2){
                jButton18.setText("|");
                jButton18.setEnabled(false);
                if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                    jButton19.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
        }
            if(move[i] == 3 && move[i+1] ==4){
                jButton20.setText("|");
                jButton20.setEnabled(false);
              
             
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }}if(move[i] == 4 && move[i+1] == 1 ){
                jButton22.setText("-");
                jButton22.setEnabled(false);
             
              
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
        }
            if(move[i] == 4 && move[i+1] == 3){
                jButton24.setText("-");
                jButton24.setEnabled(false);
            
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
    }
}//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       jButton14.setText("-");
        jButton14.setEnabled(false);
        if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
            jButton9.setBackground(Color.RED);
            
        }
        if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.RED);
            
        }
        int[] move = meuJogo.main(modo, nivel, 2, 3);
        
        for(int i = 0 ; i < move.length; i = i + 2){
            
        
            if(move[i] == 0 && move[i+1] == 3){
                jButton4.setText("-");
                jButton4.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
            }
        }
            if(move[i] == 1 && move[i+1] == 0){
                jButton6.setText("|");
                jButton6.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
        }
            if(move[i] == 1 && move[i+1] ==2){
                jButton8.setText("|");
                jButton8.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 1 && move[i+1] ==4){
                jButton10.setText("|");
                jButton10.setEnabled(false);
               if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 2 && move[i+1] == 1 ){
                jButton12.setText("-");
                jButton12.setEnabled(false);
    
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                    jButton7.setBackground(Color.BLUE);
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            
            }
    
            }
            if(move[i] == 2 && move[i+1] == 3){
                jButton14.setText("-");
                jButton14.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                    jButton9.setBackground(Color.BLUE);
                    
                }
    
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] == 0){
                jButton16.setText("|");
                jButton16.setEnabled(false);
              if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==2){
                jButton18.setText("|");
                jButton18.setEnabled(false);
                if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                    jButton19.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==4){
                jButton20.setText("|");
                jButton20.setEnabled(false);
              
             
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }if(move[i] == 4 && move[i+1] == 1 ){
                jButton22.setText("-");
                jButton22.setEnabled(false);
             
              
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 4 && move[i+1] == 3){
                jButton24.setText("-");
                jButton24.setEnabled(false);
            
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
        }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
            jButton16.setText("|");
        jButton16.setEnabled(false);
        if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.red);
            
        }
        int[] move = meuJogo.main(modo, nivel, 3, 0);
       
        for(int i = 0 ; i < move.length-1; i = i + 2){
            
        
            if(move[i] == 0 && move[i+1] == 3){
                jButton4.setText("-");
                jButton4.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
        }
            if(move[i] == 1 && move[i+1] == 0){
                jButton6.setText("|");
                jButton6.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 1 && move[i+1] ==2){
                jButton8.setText("|");
                jButton8.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
    
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 1 && move[i+1] ==4){
                jButton10.setText("|");
                jButton10.setEnabled(false);
               if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 2 && move[i+1] == 1 ){
                jButton12.setText("-");
                jButton12.setEnabled(false);
    
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                    jButton7.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            
            }
    
            }
            if(move[i] == 2 && move[i+1] == 3){
                jButton14.setText("-");
                jButton14.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                    jButton9.setBackground(Color.BLUE);
                    
                }
    
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] == 0){
                jButton16.setText("|");
                jButton16.setEnabled(false);
              if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
        
        if(move[i] == 3 && move[i+1] ==2){
            jButton18.setText("|");
            jButton18.setEnabled(false);
            if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
                
            }
           
             if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.BLUE);
        }
        }
        if(move[i] == 3 && move[i+1] ==4){
            jButton20.setText("|");
            jButton20.setEnabled(false);
          
         
             if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.BLUE);
             }
        }if(move[i] == 4 && move[i+1] == 1 ){
            jButton22.setText("-");
            jButton22.setEnabled(false);
         
          
             if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.BLUE);
        }
        }
        if(move[i] == 4 && move[i+1] == 3){
            jButton24.setText("-");
            jButton24.setEnabled(false);
        
             if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.BLUE);
        }
        }
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        jButton18.setText("|");
        jButton18.setEnabled(false);
        if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.red);
            
        }
        if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.red);
            
        }
        int[] move = meuJogo.main(modo, nivel, 3, 2);
        for(int i = 0 ; i < move.length-1; i = i + 2){
            
        
            if(move[i] == 0 && move[i+1] == 3){
                jButton4.setText("-");
                jButton4.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
        }
            if(move[i] == 1 && move[i+1] == 0){
                jButton6.setText("|");
                jButton6.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
        }
            if(move[i] == 1 && move[i+1] ==2){
                jButton8.setText("|");
                jButton8.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 1 && move[i+1] ==4){
                jButton10.setText("|");
                jButton10.setEnabled(false);
               if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 2 && move[i+1] == 1 ){
                jButton12.setText("-");
                jButton12.setEnabled(false);
    
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                    jButton7.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            
            }
    
            }
            if(move[i] == 2 && move[i+1] == 3){
                jButton14.setText("-");
                jButton14.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                    jButton9.setBackground(Color.BLUE);
                    
                }
    
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] == 0){
                jButton16.setText("|");
                jButton16.setEnabled(false);
              if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==2){
                jButton18.setText("|");
                jButton18.setEnabled(false);
                if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                    jButton19.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==4){
                jButton20.setText("|");
                jButton20.setEnabled(false);
              
             
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
                 }
            }if(move[i] == 4 && move[i+1] == 1 ){
                jButton22.setText("-");
                jButton22.setEnabled(false);
             
              
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 4 && move[i+1] == 3){
                jButton24.setText("-");
                jButton24.setEnabled(false);
            
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
       jButton20.setText("|");
        jButton20.setEnabled(false);
        if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.red);
        }
        int[] move = meuJogo.main(modo, nivel, 3, 4);
        
        for(int i = 0 ; i < move.length-1; i = i + 2){
            
        
            if(move[i] == 0 && move[i+1] == 3){
                jButton4.setText("-");
                jButton4.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
        }
            if(move[i] == 1 && move[i+1] == 0){
                jButton6.setText("|");
                jButton6.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
        }
            if(move[i] == 1 && move[i+1] ==2){
                jButton8.setText("|");
                jButton8.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 1 && move[i+1] ==4){
                jButton10.setText("|");
                jButton10.setEnabled(false);
               if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 2 && move[i+1] == 1 ){
                jButton12.setText("-");
                jButton12.setEnabled(false);
    
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                    jButton7.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            
            }
    
            }
            if(move[i] == 2 && move[i+1] == 3){
                jButton14.setText("-");
                jButton14.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                    jButton9.setBackground(Color.BLUE);
                    
                }
    
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] == 0){
                jButton16.setText("|");
                jButton16.setEnabled(false);
              if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==2){
                jButton18.setText("|");
                jButton18.setEnabled(false);
                if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                    jButton19.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==4){
                jButton20.setText("|");
                jButton20.setEnabled(false);
              
             
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
                 }
            }if(move[i] == 4 && move[i+1] == 1 ){
                jButton22.setText("-");
                jButton22.setEnabled(false);
             
              
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 4 && move[i+1] == 3){
                jButton24.setText("-");
                jButton24.setEnabled(false);
            
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        jButton22.setText("-");
        jButton22.setEnabled(false);
        if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.red);
        }
        
        int[] move = meuJogo.main(modo, nivel, 4, 1);
        
       
         for(int i = 0 ; i < move.length-1; i = i + 2){
            
        
            if(move[i] == 0 && move[i+1] == 3){
                jButton4.setText("-");
                jButton4.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
        }
            if(move[i] == 1 && move[i+1] == 0){
                jButton6.setText("|");
                jButton6.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
        }
            if(move[i] == 1 && move[i+1] ==2){
                jButton8.setText("|");
                jButton8.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 1 && move[i+1] ==4){
                jButton10.setText("|");
                jButton10.setEnabled(false);
               if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 2 && move[i+1] == 1 ){
                jButton12.setText("-");
                jButton12.setEnabled(false);
    
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                    jButton7.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            
            }
    
            }
            if(move[i] == 2 && move[i+1] == 3){
                jButton14.setText("-");
                jButton14.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                    jButton9.setBackground(Color.BLUE);
                    
                }
    
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] == 0){
                jButton16.setText("|");
                jButton16.setEnabled(false);
              if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==2){
                jButton18.setText("|");
                jButton18.setEnabled(false);
                if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                    jButton19.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==4){
                jButton20.setText("|");
                jButton20.setEnabled(false);
              
             
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
                 }
            }if(move[i] == 4 && move[i+1] == 1 ){
                jButton22.setText("-");
                jButton22.setEnabled(false);
             
              
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 4 && move[i+1] == 3){
                jButton24.setText("-");
                jButton24.setEnabled(false);
            
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        jButton24.setText("-");
        jButton24.setEnabled(false);
        if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.red);
            
        }
        int[] move = meuJogo.main(modo, nivel, 4, 3);
        
        for(int i = 0 ; i < move.length-1; i = i + 2){
            
      
            if(move[i] == 0 && move[i+1] == 3){
                jButton4.setText("-");
                jButton4.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
        }
            if(move[i] == 1 && move[i+1] == 0){
                jButton6.setText("|");
                jButton6.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
        }
            if(move[i] == 1 && move[i+1] ==2){
                jButton8.setText("|");
                jButton8.setEnabled(false);
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                jButton7.setBackground(Color.BLUE);
            }
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 1 && move[i+1] ==4){
                jButton10.setText("|");
                jButton10.setEnabled(false);
               if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                jButton9.setBackground(Color.BLUE);
                
            }
            }
            if(move[i] == 2 && move[i+1] == 1 ){
                jButton12.setText("-");
                jButton12.setEnabled(false);
    
                if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
                    jButton7.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            
            }
    
            }
            if(move[i] == 2 && move[i+1] == 3){
                jButton14.setText("-");
                jButton14.setEnabled(false);
                if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
                    jButton9.setBackground(Color.BLUE);
                    
                }
    
                 if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                jButton19.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] == 0){
                jButton16.setText("|");
                jButton16.setEnabled(false);
              if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
            if(move[i] == 3 && move[i+1] ==2){
                jButton18.setText("|");
                jButton18.setEnabled(false);
                if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
                    jButton19.setBackground(Color.BLUE);
                    
                }
               
                 if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
                jButton17.setBackground(Color.BLUE);
            }
            }
        
        if(move[i] == 3 && move[i+1] ==4){
            jButton20.setText("|");
            jButton20.setEnabled(false);
          
         
             if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.BLUE);
             }
        }if(move[i] == 4 && move[i+1] == 1 ){
            jButton22.setText("-");
            jButton22.setEnabled(false);
            if(!(jButton4.isEnabled()) && !(jButton8.isEnabled()) && !(jButton10.isEnabled()) && !(jButton14.isEnabled())){
            jButton9.setBackground(Color.BLUE);
        }
             if(!(jButton8.isEnabled()) && !(jButton6.isEnabled()) && !(jButton12.isEnabled())){
            jButton7.setBackground(Color.BLUE);
        }
             if(!(jButton12.isEnabled()) && !(jButton16.isEnabled()) && !(jButton18.isEnabled()) && !(jButton22.isEnabled())){
            jButton17.setBackground(Color.BLUE);
        }
          
        }
        if(move[i] == 4 && move[i+1] == 3){
            jButton24.setText("-");
            jButton24.setEnabled(false);
        
             if(!(jButton14.isEnabled()) && !(jButton18.isEnabled()) && !(jButton24.isEnabled()) && !(jButton20.isEnabled())){
            jButton19.setBackground(Color.BLUE);
        }
        }
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
